# Generated by Django 3.0.5 on 2020-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='img',
            field=models.ImageField(default='', upload_to='tutorial/images'),
        ),
    ]
