# Generated by Django 3.0.5 on 2020-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_list_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='img',
            field=models.ImageField(upload_to='tutorial/images'),
        ),
    ]
