# Generated by Django 3.0.5 on 2020-04-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200427_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tutorial/images'),
        ),
    ]
