# Generated by Django 3.1 on 2020-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20200429_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='vid',
            field=models.FileField(blank=True, null=True, upload_to='tutorial/videos'),
        ),
    ]
